import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * ts-rs 绑定守卫（类型自动生成）。
 *
 * `src/types/bindings/` 由 Rust 侧 `cargo test export_bindings` 生成，是
 * Rust DTO 与前端手写类型的对照源。这里从消费端再守一道：
 * - 关键绑定文件必须存在且为可解析的 TS 导出（防误删 / 生成失败静默提交空目录）；
 * - 生成文件不得出现 `bigint`（Tauri IPC 走 JSON，64 位整数在 Rust 侧已用
 *   `#[ts(type = "number")]` 覆盖，若再出现说明覆盖被漏掉）。
 */
const BINDINGS_DIR = join(__dirname, '../types/bindings')

/** 每个跨 IPC 的 DTO 对应一个绑定文件；新增 DTO 时在此登记。 */
const EXPECTED = [
  'BatchExecItem.ts',
  'GeneratedKeypair.ts',
  'HostConfigDraft.ts',
  'KnownHostEntry.ts',
  'KnownHostsSnapshot.ts',
  'NetworkDiagnostic.ts',
  'PartitionMetric.ts',
  'PortForwardInfo.ts',
  'ProcessInfo.ts',
  'RecordingMeta.ts',
  'ServerMetrics.ts',
  'SessionInfo.ts',
  'SftpChunk.ts',
  'SftpDiskTransferInfo.ts',
  'SftpDiskTransferStart.ts',
  'SftpDiskUploadPick.ts',
  'SftpEntry.ts',
  'SftpTransferStart.ts',
  'SshConfigEntry.ts',
  'SshKeyEntry.ts',
  'SyncPlan.ts',
  'SyncPlanEntry.ts',
  'SyncProgress.ts',
  'SyncStartInfo.ts'
]

describe('ts-rs 绑定目录', () => {
  it('所有关键绑定存在且含导出声明', () => {
    const present = new Set(readdirSync(BINDINGS_DIR))
    for (const file of EXPECTED) {
      expect(present, `缺少绑定 ${file}——Rust DTO 导出是否被删除？`).toContain(file)
      const text = readFileSync(join(BINDINGS_DIR, file), 'utf8')
      expect(text, `${file} 应包含 export 声明`).toMatch(/export (type|interface|enum) /)
    }
  })

  it('绑定中不得出现 bigint（IPC 走 JSON，64 位整数须为 number）', () => {
    for (const file of readdirSync(BINDINGS_DIR)) {
      if (!file.endsWith('.ts')) continue
      const text = readFileSync(join(BINDINGS_DIR, file), 'utf8')
      expect(text, `${file} 出现 bigint`).not.toMatch(/\bbigint\b/)
    }
  })

  it('绑定文件未被手改（仍带 ts-rs 生成头）', () => {
    for (const file of readdirSync(BINDINGS_DIR)) {
      if (!file.endsWith('.ts')) continue
      const text = readFileSync(join(BINDINGS_DIR, file), 'utf8')
      expect(text, `${file} 缺少生成头，疑似手改`).toContain('This file was generated by')
    }
  })
})
