// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一台会话的批量执行结果。
 */
export type BatchExecItem = { sessionId: number, name: string, ok: boolean, output: string, error: string | null, durationMs: number, truncated: boolean, };
