// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 启动参数解析出的连接意图。
 */
export type CliConnectPayload = { 
/**
 * `adhoc` = 临时目标（`user@host[:port]`）；`profile` = 主机档案名。
 */
kind: string, 
/**
 * `adhoc` 时的登录用户（`user@host` 里 `@` 前的部分，可省略）。
 */
user: string | null, 
/**
 * `adhoc` 时的目标地址。
 */
host: string | null, 
/**
 * `adhoc` 时的端口（`host:port` 里可省略，默认 22 由前端处理）。
 */
port: number | null, 
/**
 * `profile` 时的档案名。
 */
name: string | null, };
