// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeneratedKeypair = { privatePath: string, publicPath: string, 
/**
 * OpenSSH 单行公钥（含类型、base64 与备注），可直接贴到服务端 authorized_keys。
 */
publicKey: string, keyType: string, fingerprint: string, };
