// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 主机档案写回 `~/.ssh/config` 的草稿（不含任何凭据，私钥只写路径）。
 */
export type HostConfigDraft = { 
/**
 * Host 模式（即主机档案名称）。
 */
name: string, hostname: string, port: number, user: string, 
/**
 * 私钥路径；仅当连接方式为密钥认证时提供。
 */
identityFile: string | null, };
