// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KnownHostEntry } from "./KnownHostEntry";

export type KnownHostsSnapshot = { path: string, entries: Array<KnownHostEntry>, };
