// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PortForwardInfo = { id: number, sessionId: number, direction: string, bindHost: string, bindPort: number, targetHost: string, targetPort: number, };
