// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProcessInfo = { pid: number, name: string, cpuPercent: number, memoryPercent: number, };
