// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartitionMetric } from "./PartitionMetric";

export type ServerMetrics = { sessionId: number, hostname: string, os: string, cpuCores: number, load1m: number, cpuPercent: number | null, partitions: Array<PartitionMetric>, memoryTotalKb: number, memoryAvailableKb: number, diskTotalKb: number, diskUsedKb: number, diskAvailableKb: number, networkRxBytes: number, networkTxBytes: number, collectedAt: number, };
