// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionInfo = { id: number, name: string, host: string, port: number, username: string, status: string, reason: string | null, };
