// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SftpChunk = { data: string, done: boolean, transferred: number, total: number, };
