// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SftpEntry = { name: string, path: string, kind: string, size: number, modifiedAt: number | null, permissions: number | null, owner: string | null, group: string | null, };
