// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SftpDiskTransferStart = { transferId: number, total: number, resumed: boolean, 
/**
 * 真实本地路径。令牌/对话框流程中它本就留在 Rust 侧；这里回传给前端
 * 仅用于传输队列持久化（重启后续传需要），发起上传的令牌安全边界不变。
 */
localPath: string, };
