// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SftpDiskTransferInfo = { transferId: number, sessionId: number, direction: string, fileName: string, remotePath: string, localPath: string, transferred: number, total: number, done: boolean, cancelled: boolean, error: string | null, 
/**
 * 当前限速（KB/s，0 表示不限速）。
 */
speedLimitKbs: number, };
