// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SshConfigEntry = { host: string, hostname: string | null, port: number | null, user: string | null, identityFile: string | null, };
