// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SshKeyEntry = { 
/**
 * 主文件名：私钥名（有私钥时）或 `.pub` 去掉后缀的名。
 */
fileName: string, 
/**
 * `key` = 密钥（私钥或公钥）；`other` = 目录里的其它文件（config、known_hosts 等）。
 */
kind: string, hasPrivate: boolean, hasPublic: boolean, keyType: string | null, fingerprint: string | null, comment: string | null, 
/**
 * 私钥是否带口令（OpenSSH 格式；其它格式无法判断时保持 false）。
 */
encrypted: boolean, size: number, modifiedMs: number, privatePath: string | null, publicPath: string | null, };
