// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单条同步动作。`action`：`mkdir`（建目录）/ `add`（新增）/ `update`（更新）/ `skip`（跳过）。
 */
export type SyncPlanEntry = { 
/**
 * 相对路径，一律使用 `/` 分隔，不含 `..` 与前导分隔符。
 */
relativePath: string, action: string, 
/**
 * 文件字节数（目录为 0）。
 */
size: number, };
