// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncProgress = { v: number, sessionId: number, direction: string, doneFiles: number, totalFiles: number, doneBytes: number, totalBytes: number, currentFile: string | null, finished: boolean, cancelled: boolean, errors: Array<string>, };
