// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncPlanEntry } from "./SyncPlanEntry";

export type SyncPlan = { sessionId: number, direction: string, localDir: string, remoteDir: string, entries: Array<SyncPlanEntry>, 
/**
 * 将实际传输的文件数（add + update）。
 */
transferCount: number, skipCount: number, 
/**
 * 将实际传输的字节总量。
 */
totalBytes: number, };
